### ISSUE TITLE
"Cannot use Config as Config" issue in backend

### ISSUE THREAD

**Issue by sanderha** [milkyway-multimedia/ss-mwm#10]
I am getting this only sometimes getting this issue in the backend. I installed this module by installing the ss-order-history module. It seems there might be a problem with namespaces, which causes this error?

Any help would be appreciated :)

**Comment by mi3ll** [comment]
Hmm... That's unusual... Can you tell me which version of PHP you are using?

**Comment by sanderha** [comment]
I am using php 5.6.
@wernerkrauss seems to have solved the issue though :)
